config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get '/home', to: 'pages#home'

  resources :recipes do
    member do
      post 'like'
    end
    resources :reviews
  end

  resources :chefs, except:[:new]
    get '/register', to: 'chefs#new'

  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get 'logout', to: 'logins#destroy'

  resources :styles, only:[:new, :create,:show]

  resources :ingredients, only:[:new, :create,:show]

  match ':controller(/:action(/:id(.:format)))', via: :any
end

app/views/pages/home.html.erb
<div class="center-block jumbotron">
  <h1>Welcome to MyRecipes App</h1>
  <h2> This is the home page of a professionally designed recipe site</h2>
  <%= link_to 'Sign up Now !',register_path,class:"btn btn-lg btn-success" %>
</div>
<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">
      View recipes as guest user
    </h3>
    <h2 class="left">
      Browse and view recipes as a guest and
      sign up later
    </h2>
    <p><%= link_to 'Browse recipe listings',recipes_path,class: "btn btn-warning btn-small"%></p>
  </div>
  <div class="col-lg-4">
      <h3 class="midrow">
        Sign into your account
      </h3>
      <h2 class="left">
        Add/Update your recipes/create reviews like/dislike recipes and much much more
      </h2>
      <p><%= link_to 'Log into your account',login_path,class: "btn btn-warning btn-small"%></p>
   </div>
    <div class="col-lg-4">
        <h3 class="midrow">
          View recipes as guest user
        </h3>
        <h2 class="left">
          Browse and view recipes as a guest and
          sign up later
        </h2>
        <p><%= link_to 'Browse recipe listings',recipes_path,class: "btn btn-warning btn-small"%></p>
    </div>
</div>