config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get '/home', to: 'pages#home'

  resources :recipes do
    member do
      post 'like'
    end
    resources :reviews
  end

  resources :chefs, except:[:new]
    get '/register', to: 'chefs#new'

  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get 'logout', to: 'logins#destroy'

  resources :styles, only:[:new, :create,:show]

  resources :ingredients, only:[:new, :create,:show]

  match ':controller(/:action(/:id(.:format)))', via: :any
end

app/views/misc/navbar.html.erb
<header>

  <div class="row">
    <nav class="navbar navbar-fixed-top navbar-default" role="navigation">
      <%=  link_to 'myRecipes',root_path, class:"btn btn-lg btn-success", id:"logo" %>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse " id="collapse">

        <ul class="nav navbar-nav nav-ul-item">

          <li class="dropdown">
            <%= link_to '#',class:"btn btn-lg btn-danger dropdown-toggle", "data-toggle" =>"dropdown" do%>
                Styles<b class="caret"></b>
            <%end%>
            <ul class="dropdown-menu">
              <%Style.all.each do |style|%>
                  <li><%= link_to style.name, style_path(style) %></li>
              <%end%>
              <%if logged_in?%>
                  <li class="divider"></li>
                  <li>
                    <%= link_to(new_style_path) do %>
                        New Style
                    <%end%>
                  </li>

              <%end%>

            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav nav-ul-item">
          <li class="dropdown">
            <%= link_to '#',class:"btn btn-lg btn-danger dropdown-toggle", "data-toggle" =>"dropdown" do%>
                Ingredients<b class="caret"></b>
            <%end%>
            <ul class="dropdown-menu">
              <%Ingredient.all.each do |ingredient|%>
                  <li><%= link_to ingredient.name, ingredient_path(ingredient) %></li>
              <%end%>
              <%if logged_in?%>
                  <li class="divider"></li>
                  <li>
                    <%= link_to(new_ingredient_path) do %>
                        New Ingredient
                    <%end%>
                  </li>

              <%end%>


            </ul>
          </li>
          <%if logged_in?%>
              <div class="nav-ul-item">
                <li>
                  <%= link_to 'New Recipe',new_recipe_path,class:"btn btn-lg btn-warning"%>
                </li>

              </div>
              <ul class="nav-item">
                <li class="dropdown">
                  <%= link_to '#',class:"btn btn-lg btn-danger dropdown-toggle", "data-toggle" =>"dropdown" do%>
                      <%= current_user.chefname %> <b class="caret"></b>
                  <%end%>
                  <ul class="dropdown-menu">
                    <li><%= link_to "View profile",chef_path(current_user) %></li>
                    <li><%= link_to "Edit profile",edit_chef_path(current_user) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Log out",logout_path %></li>
                  </ul>
                </li>
              </ul>


          <%else%>
              <div class="nav-item">
                <%= link_to "Log in",login_path, class:"btn btn-lg btn-danger" %>
              </div>

          <%end%>
        </ul>

      </div>



    </nav>
  </div>
</header>